name: Atul Manual

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

env:
  name: atul kumar pandey

jobs:
  job_first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is my name $name

      - name: Run a multi-line script
        run: |
          echo multi line 1 - $name
          echo multi line 2 - $name
  job_secnod:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is writtern by me

      - name: Run a multi-line script
        run: |
          echo this is multi line script line one
          echo this is multi line script line two 

  